CREATE TABLE IF NOT EXISTS `linktrees` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `custom_url` VARCHAR(100) UNIQUE NOT NULL,
  `url_logo` VARCHAR(500) DEFAULT NULL,
  `deskripsi` TEXT NOT NULL,
  `html_content` LONGTEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `linktree_links` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `linktree_id` INT NOT NULL,
  `url` VARCHAR(500) NOT NULL,
  `urutan` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`linktree_id`) REFERENCES `linktrees`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
